### ISSUE TITLE
Si sale usuario salen todos

### ISSUE THREAD

**Issue by PauBatet** [pes2324q2-gei-upc/ppf-chat-engine#14]
La desconexión de un usuario causa la desconexión de todos los demas usuarios conectados al WebSocket en ese momento.

Para reproducir el error, sigue estos pasos:
1. Conecta dos o mas usuarios al WebSocket con tu herramienta de preferencia.
2. Testea que la conección funciona enviando un mensaje desde un usuario, y comprobando que llega a los otros.
3. Desconecta a un usuario.
4. Cuando mires el estado de la conexión de los otros usuarios, deberias ver que se han desconectado tambien.

El bug pasa de manera consistente en mi ordenador por lo menos, agradeceria que alguien mas lo pruebe para confirmar que no es un problema de configuración oscuro de mi parte.

**Comment by pg-goose** [comment]
fixed!
